### ISSUE TITLE
--television_destination does not work as expected

### ISSUE THREAD

**Issue by nation-wide** [jkwill87/mnamer#1]
Here's an example how to reproduce:

`touch /tmp/the.daily.show.2018.03.12.junot.diaz.1080p.web.x264-tbs.mkv`

`mnamer /tmp/the.daily.show.2018.03.12.junot.diaz.1080p.web.x264-tbs.mkv --batch --television_destination /tmp`

Starting mnamer

Detected File
the.daily.show.2018.03.12.junot.diaz.1080p.web.x264-tbs.mkv

Query Results
  [1] The Daily Show - 23x71 - March 12, 2018

Processing File
  - moving to '/tmp/The Daily Show - S23E71 - March 12, 2018.mkv'
  - Success!

Successfully processed 1 out of 1 files

`ls "/tmp/The Daily Show - S23E71 - March 12, 2018.mkv"`
ls: cannot access '/tmp/The Daily Show - S23E71 - March 12, 2018.mkv': No such file or directory

`ls /tmp/the*`
/tmp/the.daily.show.2018.03.12.junot.diaz.1080p.web.x264-tbs.mkv

**Comment by jkwill87** [comment]
Hey, thanks for posting this issue! I noticed the bug a couple of weeks ago but forgot to follow up on it  😅-- I'll look into sorting it out later tonight.

**Comment by nation-wide** [comment]
Excellent, thank you! 😃
