### ISSUE TITLE
Unable to force TVDB ID

### ISSUE THREAD

**Issue by steckums** [jkwill87/mnamer#10]
Running into issues with file names similar to this:

`The.Flash.2014.S04E18.1080p.HDTV.x264-PLUTONiUM.mkv`

The TVDB ID of this series is `279121`

Here is the output of GuessIt:

> For: The.Flash.2014.S04E18.1080p.HDTV.x264-PLUTONiUM.mkv
GuessIt found: {
    "title": "The Flash",
    "year": 2014,
    "season": 4,
    "episode": 18,
    "screen_size": "1080p",
    "format": "HDTV",
    "video_codec": "h264",
    "release_group": "PLUTONiUM",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}

I'm assuming that it searches TVDB and finds the show "The Flash" (ID `78650`), but there was only one season so it returns nothing. However, running the command...

`mnamer The.Flash.2014.S04E18.1080p.HDTV.x264-PLUTONiUM.mkv --id 279121`

... still doesn't find anything.

**Comment by jkwill87** [comment]
Hey, thanks for submitting this bug and helping to improve the project. This fix will be included in release 1.3 coming out later this week 🙂.
