### ISSUE TITLE
No matching withwrong date in file's name

### ISSUE THREAD

**Issue by waenhill** [jkwill87/mnamer#104]
Hello,
I would like to do a suggestion based on the bellow issue that I had:

- I have a Movie named like that: 

```
Movies/MyMovie.2014.FR.720p/MyMovie.2014.FR.720p.avi
Movies/MyMovie.2014.FR.720p/film.nfo
```

Here the year in the name is wrong and it should be 2015. As a consequence the scrapper (tmbd / omdb) don't gives any result.

- So I have renamed the file and folder like so:

```
Movies/MyMovie.FR.720p/MyMovie.FR.720p.avi
Movies/MyMovie.FR.720p/film.nfo
```

- And there is is working perfectly and gave me the result:

```
Movies/My Movie (2015)/My Movie (2015).avi
Movies/My Movie (2015)/My Movie (2015).nfo
```

If I check on TVDB site there is only one match when I search this movie's title.

**So here is my suggestion**: Could it be possible that, when there has been no match with the year criteria, its search for movie again but without date and take result if there is not too much matches?

Please let me know your concerns.
Thank you.

**Comment by jkwill87** [comment]
Should be fixed in db4007f1e50436403cbfee10f067de5fd82a55d6. Year searches should now allow a 5-year tolerance.

**Comment by waenhill** [comment]
Thanks a lot

**Comment by thri1hous** [comment]
so i think this may have introduced a new issue, when you have the right date but there is an other similar title within 5 years, it grabs the wrong one, can we have a command line flag that disables the 5 year tolerance or allows you to set it from 1 to whatever ?
