### ISSUE TITLE
Renaming TV episodes for season 0

### ISSUE THREAD

**Issue by EmptyJay** [jkwill87/mnamer#113]
When renaming TV episodes for Season 0 of a show, the resulting filename ends up with no number for the season. S00E05 gets turned into SE05.

**Comment by EmptyJay** [comment]
I've only been using mnamer for a day, but I love it and it's completely taken over my process.

**Comment by jkwill87** [comment]
Thanks! I recently added proper support for special season episodes, just haven't put out a new release yet. I'm still working on a couple of other things first but it should be out soon enough. Either stay tuned or you can test it out early by [installing off the master branch](https://github.com/jkwill87/mnamer/wiki/Installation#installing-latest-wip-version-from-github) 😄 .

**Comment by EmptyJay** [comment]
Will do. Thanks!
