### ISSUE TITLE
ARM Version on Dockerhub ?

### ISSUE THREAD

**Issue by HydrelioxGitHub** [jkwill87/mnamer#125]
Hello,
I'm very interested in your project. I 've seen there is an image on docker hub, but my docker setup is on a rasperry pi. Is it possible to publish an ARM compatible version ?

**Comment by jkwill87** [comment]
The `python:alpine` image lists support for ARM and AFAIK all of mnamer's dependencies are pure Python so I'd assume that it should work as-is?

![image](https://user-images.githubusercontent.com/4343678/106370605-8fa9a200-6329-11eb-96bd-1b172ea48d54.png)

I don't have any ARM devices presently or any experience developing cross architecture Dockerfiles so I can't say myself.

**Comment by HydrelioxGitHub** [comment]
Thank for your answer. Could anyone help me with the dockerfile I have to create to make this works ? I'm a noob with docker. All I know is pull images from dockerhub and run it in portainer.

**Comment by HydrelioxGitHub** [comment]
I've used the exact same dockerfile provided in the repository and it seems to work.

![image](https://user-images.githubusercontent.com/15862735/109095001-3744a500-771b-11eb-9649-b83fc3d92922.png)

I've to set up the configuration now. Thanks for your help !
