### ISSUE TITLE
Can't match show when names are similar

### ISSUE THREAD

**Issue by Rambomst** [jkwill87/mnamer#16]
I am trying to rename `Deception (2018) S01E12` however no show is detected. I can see it on the tvdb and the name matches. I have tried several variations but none seem to work.

There are several shows with the name `Deception`, if the file was named just `Deception S01E12` shouldn't it give several options to choose from?

**Comment by Rambomst** [comment]
I am having another issue where `Colony` is being detected as `The Colony` even though there is a show listed on tvdb as `Colony`

**Comment by jkwill87** [comment]
Yea, I'm able to reproduce these issues too, thanks for reporting them. They are listed on TVDb so there isn't a reason why they shouldn't be detected properly.

I'll try to get this sorted by the next release sometime next month 😃
