### ISSUE TITLE
Seeing issues with thetvdb but the TVDB API is up. 

### ISSUE THREAD

**Issue by lozbrown** [jkwill87/mnamer#17]
Suddenly seeing issues with the TVDB scraping, i wonder if it could be to do with this 

>From what I can see, the tvdb api has removed all the spaces in its api which is causing the scraper's regexes to fail, since they have a lot of hard-coded spaces.

https://forums.thetvdb.com/viewtopic.php?f=17&t=48331

> mnamer --test_run The.Expanse.S03E08.HDTV.x264-SVA\[rarbg\]/The.Expanse.S03E08.HDTV.x264-SVA.mkv
> Starting mnamer
>   - success loading config from /home/loz/.mnamer.json
> 
> Detected File
> The.Expanse.S03E08.HDTV.x264-SVA.mkv
> 
> Query Results
> Traceback (most recent call last):
>   File "/usr/local/bin/mnamer", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.6/dist-packages/mnamer/__main__.py", line 533, in main
>     process_files(targets, media, test_run, id_key, **config)
>   File "/usr/local/lib/python3.6/dist-packages/mnamer/__main__.py", line 371, in process_files
>     hit = next(results)
>   File "/usr/local/lib/python3.6/dist-packages/mnamer/__main__.py", line 229, in provider_search
>     api, api_key=keys.get(api)
>   File "/usr/local/lib/python3.6/dist-packages/mapi/providers.py", line 64, in provider_factory
>     }[provider.lower()](**options)
>   File "/usr/local/lib/python3.6/dist-packages/mapi/providers.py", line 293, in __init__
>     self.token = endpoints.tvdb_login(self.api_key)
>   File "/usr/local/lib/python3.6/dist-packages/mapi/endpoints.py", line 342, in tvdb_login
>     assert status == 200 and content.get('token')  # TVDb down or unavailable?
> AssertionError

**Comment by jkwill87** [comment]
The TVDb has been really unreliable the last couple of days. That is an interesting issue and one that I'll double check I have test cases for but I either way it seems to be working now.

```
Starting mnamer

Detected File
The.Expanse.S03E08.HDTV.x264-SVA.mkv

Query Results
  [1] The Expanse - 03x08 - It Reaches Out
  [RETURN] for default, [s]kip, [q]uit
  > Your Choice? s
  - Skipping rename, as per user request.

Successfully processed 0 out of 1 files
```

btw I'm also feeling the expanse, I'm only on season 1 though 😜
