### ISSUE TITLE
Format placeholder for episodes {year} not working

### ISSUE THREAD

**Issue by bjoern-vh** [jkwill87/mnamer#186]
Hello,

I just tested and found that when renaming episodes, the {year} placeholder does not work. It's always empty.
For movies it is ok.

Example: `--episode-format='{series[0]}/{series} ({year})/{series} - S{season:02}E{episode:02} - {title}.{extension}`
=> expected: `B/Better Call Saul (2015)/Better Call Saul - S01E01 - Title.mkv`
=> result: `B/Better Call Saul /Better Call Saul - S01E01 - Title.mkv`

**Comment by msdos** [comment]
I think this would be a feature actually... in https://github.com/jkwill87/mnamer/wiki/Formatting it says that year is for media type `Movie`. Actually, I think this issue is a duplicate for https://github.com/jkwill87/mnamer/issues/89.
