### ISSUE TITLE
This doesn't appear to work

### ISSUE THREAD

**Issue by lozbrown** [jkwill87/mnamer#2]
After installing with pip 

First attempt crashes, is some dependancy missing that pip didnt install

>  loz@gravity:/media/media1/Unsorted-Downloads$ mnamer
> Traceback (most recent call last):
>   File "/usr/local/bin/mnamer", line 11, in <module>
>     load_entry_point('mnamer==1.2', 'console_scripts', 'mnamer')()
>   File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
>     return ep.load()
>   File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2324, in load
>     return self.resolve()
>   File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/usr/local/lib/python3.5/dist-packages/mnamer/__main__.py", line 32, in <module>
>     from mapi.providers import provider_factory
>   File "/usr/local/lib/python3.5/dist-packages/mapi/providers.py", line 10, in <module>
>     from mapi import endpoints
>   File "/usr/local/lib/python3.5/dist-packages/mapi/endpoints.py", line 10, in <module>
>     import requests
>   File "/usr/local/lib/python3.5/dist-packages/requests/__init__.py", line 84, in <module>
>     from urllib3.contrib import pyopenssl
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
>     import OpenSSL.SSL
>   File "/usr/local/lib/python3.5/dist-packages/OpenSSL/__init__.py", line 8, in <module>
>     from OpenSSL import crypto, SSL
>   File "/usr/local/lib/python3.5/dist-packages/OpenSSL/crypto.py", line 16, in <module>
>     from OpenSSL._util import (
>   File "/usr/local/lib/python3.5/dist-packages/OpenSSL/_util.py", line 6, in <module>
>     from cryptography.hazmat.bindings.openssl.binding import Binding
>   File "/usr/local/lib/python3.5/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 157, in <module>
>     Binding.init_static_locks()
>   File "/usr/local/lib/python3.5/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 138, in init_static_locks
>     cls._ensure_ffi_initialized()
>   File "/usr/local/lib/python3.5/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 125, in _ensure_ffi_initialized
>     cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
>   File "/usr/local/lib/python3.5/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 85, in build_conditional_library
>     if not getattr(lib, condition):
> AttributeError: cffi library '_openssl' has no function, constant or global variable named 'Cryptography_HAS_SIGALGS'

**Comment by lozbrown** [comment]
loz@gravity:/media/media1/Unsorted-Downloads$ sudo -H pip install mnamer
Requirement already satisfied: mnamer in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied: appdirs in /usr/local/lib/python3.5/dist-packages (from mnamer)
Requirement already satisfied: guessit in /usr/local/lib/python3.5/dist-packages (from mnamer)
Requirement already satisfied: mapi in /usr/local/lib/python3.5/dist-packages (from mnamer)
Requirement already satisfied: termcolor in /usr/local/lib/python3.5/dist-packages (from mnamer)
Requirement already satisfied: rebulk>=0.9.0 in /usr/local/lib/python3.5/dist-packages (from guessit->mnamer)
Requirement already satisfied: babelfish>=0.5.5 in /usr/local/lib/python3.5/dist-packages (from guessit->mnamer)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.5/dist-packages (from guessit->mnamer)
Requirement already satisfied: requests in /usr/local/lib/python3.5/dist-packages (from mapi->mnamer)
Requirement already satisfied: requests_cache in /usr/local/lib/python3.5/dist-packages (from mapi->mnamer)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from rebulk>=0.9.0->guessit->mnamer)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3/dist-packages (from requests->mapi->mnamer)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.5/dist-packages (from requests->mapi->mnamer)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python3.5/dist-packages (from requests->mapi->mnamer)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.5/dist-packages (from requests->mapi->mnamer)

**Comment by jkwill87** [comment]
This appears to be an incompatibility between your system's installed openssl libs and [cryptography](https://cryptography.io/en/latest/installation/#supported-platforms) package. Similar to users who have run into [similar issues](https://github.com/mitmproxy/mitmproxy/issues/2380), please ensure that you have an OpenSSL version that is [supported by cryptography](https://cryptography.io/en/latest/installation/#supported-platforms).

**Comment by lozbrown** [comment]
I see, the standard version i Ubuntu 16.04.4 LTS seems to be 
ii  openssl                                       1.0.2g-1ubuntu4.11

which is newer than those supported by cryptography, if memory serves it was upgraded due to a critical security flaw in older versions.

I'm not even sure how I'd downgrade it now

**Comment by jkwill87** [comment]
Yea, I'm not sure but your issue has to be environment related. Here is an example of it working on a fresh Ubuntu install against the versions you provided:

![xenial](https://user-images.githubusercontent.com/4343678/38456215-0074e978-3a50-11e8-903a-8afc72178c45.gif)

**Comment by lozbrown** [comment]
This was resolved with the following commands
sudo -H pip uninstall cryptography
sudo -H pip3 uninstall cryptography
sudo -H pip3 install -U cryptography

**Comment by jkwill87** [comment]
Cool 🏂
