### ISSUE TITLE
embed application key for tmdb

### ISSUE THREAD

**Issue by ssbarnea** [jkwill87/mnamer#200]
TMDB does also provide application level keys, which are aimed to be used by application developers to embed in their apps. This means that mnamer could include such a key to allow use without requiring each user to register a way.

I wrote this because I obtained such a key by simple filing a form, the next day I got the key for mnamer. Isn't that cool?

I would not remove the ability to define a user key, as an app key might be revoked, but from from the UX point of view, that is a great improvement. Details on https://developers.themoviedb.org/3/getting-started/introduction

**Comment by jkwill87** [comment]
[mnamer does indeed embed a TMDb API key](https://github.com/jkwill87/mnamer/blob/65b7eaaaf41c7d5b03e84a235e25005108816c1e/mnamer/providers.py#L144). You may hit rate limiting using this default key, if so, as you've mentioned, you can specify your own via the `api_key_tmdb` [configuration file option](https://github.com/jkwill87/mnamer/wiki/Settings#config-only-settings).

**Comment by jkwill87** [comment]
Please let me know if I've missed something or misunderstood your suggestion-- will be happy to reopen and follow-up!

**Comment by ssbarnea** [comment]
I think tha tthe while idea of having an app key, is that this would have different rate limits, likely per IP only.
