### ISSUE TITLE
"no matches found" while using tmdb api

### ISSUE THREAD

**Issue by yuzokc** [jkwill87/mnamer#234]
I have been using mnamer without issues until last update. Since then, in every single rename I try, I get the same "no matches found" while using tmdb provider

Any though on why this is happening

Thanks in advance.

 mnamer -v --movie-api=tmdb --media=movie --no-overwrite *

system
 - date = 2023-02-25
 - platform = XXXXXXXXXXXXXX
 - arguments = ['-v', '--movie-api=tmdb', '--media=movie', '--no-overwrite', 'English.srt', 'The.Year.I.Started.Masturbating.2022.mp4']
 - cache location = XXXXXXXXXXXXXXXX
 - python version = 3.10.9
 - mnamer version = 2.5.5.dev69
 - appdirs version = 1.4.4
 - guessit version = 3.5.0
 - requests version = 2.28.2
 - requests cache version = 0.9.8
 - teletype version = 1.3.4

settings
 - targets = [PosixPath('English.srt'), PosixPath('The.Year.I.Started.Masturbating.2022.mp4')]
 - batch = False
 - lower = False
 - recurse = False
 - scene = False
 - verbose = True
 - hits = 10
 - ignore = ['.*sample.*', '^RARBG.*']
 - language = None
 - mask = ['.avi', '.m4v', '.mp4', '.mkv', '.ts', '.wmv', '.srt', '.idx', '.sub', '.ass']
 - no_guess = False
 - no_overwrite = True
 - no_style = False
 - movie_api = tmdb
 - movie_directory = None
 - movie_format = {name} [{year}].{extension}
 - episode_api = tvmaze
 - episode_directory = None
 - episode_format = {series} - S{season:02}E{episode:02} - {title}.{extension}
 - version = False
 - clear_cache = False
 - config_dump = False
 - config_ignore = False
 - config_path = None
 - id_imdb = None
 - id_tmdb = None
 - id_tvdb = None
 - id_tvmaze = None
 - no_cache = False
 - media = movie
 - test = False
 - api_key_omdb = None
 - api_key_tmdb = None
 - api_key_tvdb = None
 - api_key_tvmaze = None
 - replace_before = {}
 - replace_after = {':': ',', ';': ',', '@': 'at'}

targets
 - /00/The.Year.I.Started.Masturbating.2022/English.srt
 - /00/The.Year.I.Started.Masturbating.2022/The.Year.I.Started.Masturbating.2022.mp4
Starting mnamer

Processing Movie Subtitle "English.srt" (81.30KB)
/mnt/d/down/00/The.Year.I.Started.Masturbating.2022/English.srt
using tmdb

search parameters
 - container = .srt
 - group = None
 - language = None
 - language_sub = {'name': 'English', 'a2': 'en', 'a3': 'eng'}
 - quality = None
 - synopsis = None
 - name = The Year I Started Masturbating
 - year = 2022
 - id_imdb = None
 - id_tmdb = None
 - extension = .en.srt

no matches found
 ❱ The Year I Started Masturbating (2022) (best guess)
   skip
   quit

skipping (user request)

Processing Movie "The.Year.I.Started.Masturbating.2022.mp4" (1.91GB)
/00/The.Year.I.Started.Masturbating.2022/The.Year.I.Started.Masturbating.2022.mp4
using tmdb

search parameters
 - container = .mp4
 - group = None
 - language = None
 - language_sub = None
 - quality = None
 - synopsis = None
 - name = The Year I Started Masturbating
 - year = 2022
 - id_imdb = None
 - id_tmdb = None
 - extension = .mp4

no matches found
 ❱ The Year I Started Masturbating (2022) (best guess)
   skip
   quit

**Comment by fergie4000** [comment]
What fixed it for me was changing [this line](https://github.com/jkwill87/mnamer/blob/main/mnamer/providers.py#L185) from 
`                f"{year_from}-{year_to}",
`
to just
 `                year,
`

No results are returned when a year range is supplied.

**Comment by yuzokc** [comment]
Thank you @fergie4000, it worked for me too
