### ISSUE TITLE
Consistent poor results for movies

### ISSUE THREAD

**Issue by Shades84** [jkwill87/mnamer#256]
Testing mnamer on my own library, I'm getting some very poor results, with both tmdb and omdb apis. For example, it guessed Avatar 2009 was "Cyber Wars" 2004 and it sets the year for Black Panther as 2013, rather than the correct 2018. Do I have some sort of Metadata problem with my files? I've not dug into the source code to see how this all functions

**Comment by jkwill87** [comment]
What version of manger are you using? Likely may be resolved by https://github.com/jkwill87/mnamer/pull/248. Will cut a new release this week.

**Comment by Shades84** [comment]
I'll check it out tonight. I installed with pip, so whatever version that gives. My movies have a lot of extra stuff in the filename, perhaps that's an issue too? How fuzzy of a search can this program handle?

**Comment by jkwill87** [comment]
Updated it now, you should be able to update using `pip3 install -U mnamer` and confirm the version using `mnamer --version`. The latest release is 2.5.5.

**Comment by Shades84** [comment]
All my tests cases are working great now, even the really obscure stuff. Thank you!
