### ISSUE TITLE
more renaming options, like format and source

### ISSUE THREAD

**Issue by rodibin-at-placemaildotonline** [jkwill87/mnamer#29]
Need templates to include the option of <$format> and <$source> to rename files reading from the filename (or even better, reading the file and detecting the format... although this is probably impossible to do with source) so something like:

`/Downloads/Rick.and.Morty.S02E01.Bluray.1080p.x264-RARBG.mp4`

is turned into 
`
/Downloads/Rick and Morty - S02E01 (1080p) (Blu-ray).mp4`

**Comment by jkwill87** [comment]
I think I set up mapi to capture these fields with the intention of adding this feature (e.g. https://github.com/jkwill87/mapi/blob/730bf57c12aecaf49e18c15bf2b35af7f554b3cc/mapi/metadata.py#L19). It should be relatively straight forward to implement.

I'm going to give mnamer some love soon, just got to get through my last week of exams first 😆.

**Comment by rodibin-at-placemaildotonline** [comment]
You are absolutely brilliant 

Also, is there any way to add the television year?

**Comment by jkwill87** [comment]
In mnamer v2 video and audio quality fields have been combined into the "quality" template variable.

**Comment by Monirzadeh** [comment]
how can i get just resolution( 720p or 1080p) and not other (blue-ray etc )
