### ISSUE TITLE
mnamer doesn't recognize .mnamer.json in the user's home directory

### ISSUE THREAD

**Issue by lamahmud** [jkwill87/mnamer#33]
Hi,
I created a .mnamer.json by running the following command in my home directory:
mnamer --config_dump >.mnamer.json
I then edited the .mnamer.json file using vi to change the TV directory line to:

_"television_directory"/Volumes/Plex/TVShows/{series}/Season {season:02} "",
"television_format": "{series}.S{season:02}E{episode:02}.{title}{extension}",_

Then I then run:
_mnamer --config_dump_, it gives me the default config.   Running 
_"mnamer -b /temp/TVUploads/."_  doesn't use the new config file but uses the default config instead.  **Note:** It claims to use the .mnamer.json file but it actually doesn't
Is there a command line switch to specify the config location?  Maybe you should put one in.
I'm running MacOS 10.13.6 (High Sierra).
Output of mnamer -bv below (note the TV directory line and the TV format line aren't changed despite claiming to have loaded my custom config.

➜  ~ mnamer -bv /Volumes/MacHD/Users/user/Temp/TVUploads/.
**loaded config from /Volumes/MacHD/Users/user/.mnamer.json**

CLI Arguments
 - batch: True
 - verbose: True

Preferences
 - batch: True
 - lowercase: False
 - recurse: False
 - scene: False
 - verbose: True
 - nocache: False
 - noguess: False
 - nostyle: False
 - blacklist: ['.*sample.*', '^RARBG.*']
 - extension_mask: ['avi', 'm4v', 'mp4', 'mkv', 'ts', 'wmv']
 - hits: 5
 - movie_api: tmdb
 - movie_directory:
 - movie_format: {title} ({year}){extension}
 - television_api: tvdb
 **- television_directory:**
 **- television_format: {series} - S{season:02}E{episode:02} - {title}{extension}**
 - api_key_tmdb: db972a607f2760bb19ff8bb34074b4c7
 - api_key_tvdb: E69C7A2CEF2F3152
 - api_key_omdb: 61652c15
 - replacements: {'&': 'and', '@': 'at', ':': ',', ';': ','}

Directives
 - help: False
 - media_override: False
 - test: False
 - id: False
 - config_dump: False
 - config_ignore: False
 - media_mask: False
 - version: False

Targets
 - /Volumes/MacHD/Users/user/Temp/TVUploads/Fear the Walking Dead - S05E15 - Channel 5.mkv
 - /Volumes/MacHD/Users/user/Temp/TVUploads/Black Jesus - S03E01 - The Compton Carter.mkv
 - /Volumes/MacHD/Users/user/Temp/TVUploads/Pennyworth - S01E09 - Alma Cogan.mkv
 - /Volumes/MacHD/Users/user/Temp/TVUploads/The 100 - S06E08 - The Old Man and The Anomaly.mkv
 - /Volumes/MacHD/Users/user/Temp/TVUploads/The Terror - S02E07 - Infamy My Perfect World.mkv
 - /Volumes/MacHD/Users/user/Temp/TVUploads/The Terror - S02E06 - Infamy Taizo.mkv
 - /Volumes/MacHD/Users/user/Temp/TVUploads/The Terror - S02E05 - Infamy Shatter Like A Pearl.mkv
 - /Volumes/MacHD/Users/user/Temp/TVUploads/The Circus - S04E09 - The People on That Stage.mkv

--------------------------------------------------------------------------------

Starting mnamer

Processing Television "Fear the Walking Dead - S05E15 - Channel 5"
 - media: television
 - series: Fear the Walking Dead
 - season: 5
 - episode: 15
 - extension: .mkv
moving to /Volumes/MacHD/Users/user/Temp/TVUploads/Fear the Walking Dead - S05E15 - Channel 5.mkv
OK!

Processing Television "Black Jesus - S03E01 - The Compton Carter"
 - media: television
 - series: Black Jesus
 - season: 3
 - episode: 1
 - extension: .mkv
moving to /Volumes/MacHD/Users/user/Temp/TVUploads/Black Jesus - S03E01 - The Compton Carter.mkv
OK!

Processing Television "Pennyworth - S01E09 - Alma Cogan"
 - media: television
 - series: Pennyworth
 - season: 1
 - episode: 9
 - extension: .mkv
moving to /Volumes/MacHD/Users/user/Temp/TVUploads/Pennyworth - S01E09 - Alma Cogan.mkv
OK!

Processing Television "The 100 - S06E08 - The Old Man and The Anomaly"
 - media: television
 - series: The 100
 - season: 6
 - episode: 8
 - extension: .mkv
moving to /Volumes/MacHD/Users/user/Temp/TVUploads/The 100 - S06E08 - The Old Man and The Anomaly.mkv
OK!

Processing Television "The Terror - S02E07 - Infamy My Perfect World"
 - media: television
 - series: The Terror
 - season: 2
 - episode: 7
 - extension: .mkv
moving to /Volumes/MacHD/Users/user/Temp/TVUploads/The Terror - S02E07 - Infamy My Perfect World.mkv
OK!

Processing Television "The Terror - S02E06 - Infamy Taizo"
 - media: television
 - series: The Terror
 - season: 2
 - episode: 6
 - extension: .mkv
moving to /Volumes/MacHD/Users/user/Temp/TVUploads/The Terror - S02E06 - Infamy Taizo.mkv
OK!

Processing Television "The Terror - S02E05 - Infamy Shatter Like A Pearl"
 - media: television
 - series: The Terror
 - season: 2
 - episode: 5
 - extension: .mkv
moving to /Volumes/MacHD/Users/user/Temp/TVUploads/The Terror - S02E05 - Infamy Shatter Like A Pearl.mkv
OK!

Processing Television "The Circus - S04E09 - The People on That Stage"
 - media: television
 - series: The Circus
 - season: 4
 - episode: 9
 - extension: .mkv
moving to /Volumes/MacHD/Users/user/Temp/TVUploads/The Circus - S04E09 - The People on That Stage.mkv
OK!

8 out of 8 files processed successfully

**Comment by lamahmud** [comment]
Output of cat .mnamer.json
➜  ~ cat .mnamer.json
{
    "api_key_omdb": "61652c15",
    "api_key_tmdb": "db972a607f2760bb19ff8bb34074b4c7",
    "api_key_tvdb": "E69C7A2CEF2F3152",
    "batch": false,
    "blacklist": [
        ".*sample.*",
        "^RARBG.*"
    ],
    "extension_mask": [
        "avi",
        "m4v",
        "mp4",
        "mkv",
        "ts",
        "wmv"
    ],
    "hits": 5,
    "lowercase": false,
    "movie_api": "tmdb",
    "movie_directory": "",
    "movie_format": "{title} ({year}){extension}",
    "nocache": false,
    "noguess": false,
    "nostyle": false,
    "recurse": false,
    "replacements": {
        "&": "and",
        ":": ",",
        ";": ",",
        "@": "at"
    },
    "scene": false,
    "television_api": "tvdb",
    "television_directory"/Volumes/Plex/TVShows/{series}/Season {season:02} "",
    "television_format": "{series}.S{season:02}E{episode:02}.{title}{extension}",
    "verbose": false
}

**Comment by fajulleiro** [comment]
Yeah, I have the same problem with latest v2

**Comment by jkwill87** [comment]
It looks like there is a syntax issue with your configuration file.

`"television_directory"/Volumes/Plex/TVShows/{series}/Season {season:02} ""` isn't valid JSON. I think you would want something like `"television_directory": "/Volumes/Plex/TVShows/{series}/Season {season:02}"`.

If its any easier you can also create a config file by passing CLI variables alongside the `config-dump` command. 

e.g. `mnamer --television-directory='/Volumes/Plex/TVShows/{series}/Season {season:02}' --config-dump` will give you this:

```json
{
    "api_key_omdb": "61652c15",
    "api_key_tmdb": "db972a607f2760bb19ff8bb34074b4c7",
    "api_key_tvdb": "E69C7A2CEF2F3152",
    "batch": false,
    "blacklist": [
        ".*sample.*",
        "^RARBG.*"
    ],
    "extensions": [
        "avi",
        "m4v",
        "mp4",
        "mkv",
        "ts",
        "wmv"
    ],
    "hits": 5,
    "lowercase": false,
    "movie_api": "tmdb",
    "movie_directory": "",
    "movie_format": "{title} ({year}){extension}",
    "nocache": false,
    "noguess": false,
    "nostyle": false,
    "recurse": false,
    "replacements": {
        "&": "and",
        ":": ",",
        ";": ",",
        "@": "at"
    },
    "scene": false,
    "television_api": "tvdb",
    "television_directory": "/Volumes/Plex/TVShows/{series}/Season {season:02}",
    "television_format": "{series} - S{season:02}E{episode:02} - {title}{extension}",
    "verbose": 0
}
```

Either way, configuration handling seems to be working at the moment in the v2 branch which will be merged and released on Monday. Whether or not this was a bug it seems to be currently working as intended at the moment :sunglasses:.
