### ISSUE TITLE
Cannot use metadata in folder path

### ISSUE THREAD

**Issue by atomicmooseca** [jkwill87/mnamer#37]
The folder path is checked for existence on startup, and if the path doesn't exist, mnamer exits before doing anything. This doesn't work with a metadata format string in the folder path (it won't exist until mnamer creates it).

In **mnamer/args.py**, lines 68-70:

68|    if key.endswith("_directory") and not isdir(value):
69|    print(f"mnamer: error: {key} '{value}' cannot be found")
70|    exit(0)

Delete these lines and it works perfect.

**Comment by jkwill87** [comment]
Yea, I noticed this bug a little while back. I addressed it in my WIP v2 branch (that's taking me forever to merge :sweat_smile:).

**Comment by jkwill87** [comment]
Should be fixed in the latest version. Run`pip3 install -U mnamer` to update.
