### ISSUE TITLE
Fails to find episodes.

### ISSUE THREAD

**Issue by BeardedIT** [jkwill87/mnamer#38]
Configuration
  • movie_api: tmdb
  • television_api: tvdb
  • verbose: True
  • television_template: <$series - >< - $season>x<$episode - >< - $title><$extension>
  • extension_mask: [u'avi', u'm4v', u'mp4', u'mkv', u'ts', u'wmv']
  • scene: False
  • blacklist: [u'.*sample.*', u'^RARBG.*']
  • television_destination: None
  • movie_destination: None
  • max_hits: 15
  • movie_template: <$title ><($year)><$extension>
  • replacements: {u'@': u'at', u';': u',', u':': u',', u'&': u'and'}
  • help: False
  • recurse: False
  • batch: False
  • api_key_tvdb: RV0E698RSRTOA09L
  • api_key_tmdb: db972a607f2760bb19ff8bb34074b4c7

Detected File
Gold Rush - 10x10 -
  • series: Gold Rush
  • media: television
  • episode: 10
  • extension: .mkv
  • season: 10

Query Results
  • None found! Skipping.

Detected File
Homestead Rescue - 06x04 - Cobbers Nightmare
  • series: Homestead Rescue
  • media: television
  • episode: 4
  • extension: .mkv
  • season: 6

Query Results
  [1] Homestead Rescue - 06x04 - Cobbers Nightmare
  [RETURN] for default, [s]kip, [q]uit

**Comment by jkwill87** [comment]
Try upgrading mnamer to version 2 by running `pip3 install -U mnamer` and see if that works any better for you.
