### ISSUE TITLE
Little issue with folder and filename 

### ISSUE THREAD

**Issue by fajulleiro** [jkwill87/mnamer#39]
I have this problem with some files, that I can sort out with a little of work but it would be great if manmer could sort it out without my help. Thanks.

`xxx@xxx:~/movies/Quien a hierro mata [MicroHD 1080p][DTS 5.1-Castellano-AC3 5.1-Castellano+Subs][ES-EN] $ mnamer Quien\ a\ hierro\ mata\ M1080.www.pctnew.org.mkv

============================== CRASH REPORT BEGIN ==============================

--------------------------------- environment ----------------------------------

 - date = 2020-01-27
 - platform = Linux-4.19.66-v7+-armv7l-with-glibc2.17
 - arguments = ['Quien a hierro mata M1080.www.pctnew.org.mkv']
 - python version = 3.8.1
 - mnamer version = 2.0.0

--------------------------------- stack trace ----------------------------------

Traceback (most recent call last):
  File "/home/xxx/.pyenv/versions/3.8.1/lib/python3.8/site-packages/mnamer/__main__.py", line 32, in main
    run()
  File "/home/xxx/.pyenv/versions/3.8.1/lib/python3.8/site-packages/mnamer/__main__.py", line 48, in run
    targets = Target.populate_paths(settings)
  File "/home/xxx/.pyenv/versions/3.8.1/lib/python3.8/site-packages/mnamer/target.py", line 58, in populate_paths
    targets = [cls(file_path, settings) for file_path in file_paths]
  File "/home/xxx/.pyenv/versions/3.8.1/lib/python3.8/site-packages/mnamer/target.py", line 58, in <listcomp>
    targets = [cls(file_path, settings) for file_path in file_paths]
  File "/home/xxx/.pyenv/versions/3.8.1/lib/python3.8/site-packages/mnamer/target.py", line 42, in __init__
    self.metadata = parse_metadata(
  File "/home/xxx/.pyenv/versions/3.8.1/lib/python3.8/site-packages/mnamer/metadata.py", line 211, in parse_metadata
    metadata = Metadata(file_path=file_path, media=media_hint)
  File "<string>", line 8, in __init__
  File "/home/xxx/.pyenv/versions/3.8.1/lib/python3.8/site-packages/mnamer/metadata.py", line 63, in __post_init__
    " ".join(
TypeError: sequence item 1: expected str instance, list found

=============================== CRASH REPORT END ===============================

Dang, it looks like mnamer crashed! Please consider filling an issue at
https://github.com/jkwill87/mnamer/issues along with this report.

xxx@xxx:/movies/Quien a hierro mata [MicroHD 1080p][DTS 5.1-Castellano-AC3 5.1-Castellano+Subs][ES-EN] $ cd ..
xxx@xxx:/movies $ mv Quien\ a\ hierro\ mata\ \[MicroHD\ 1080p\]\[DTS\ 5.1-Castellano-AC3\ 5.1-Castellano+Subs\]\[ES-EN\]/ Quien\ a\ hierro\ mata
xxx@xxx:/movies $ cd Quien\ a\ hierro\ mata/
xxx@xxx:/movies/Quien a hierro mata $ mnamer  --movie-directory=~/share/kodi/movies_es Quien\ a\ hierro\ mata\ M1080.www.pctnew.org.mkv
Starting mnamer

Processing Movie "Quien a hierro mata M1080.www.pctnew.org.mkv"
no matches found
   Quien a Hierro Mata M1080 (best guess)
   skip
 ❱ quit
aborting as per user request

0 out of 1 files processed successfully
xxx@xxx:/movies/Quien a hierro mata $ mnamer  --id-tmdb=574376 --movie-directory=~/share/kodi/movies_es Quien\ a\ hierro\ mata\ M1080.www.pctnew.org.mkv
Starting mnamer

Processing Movie "Quien a hierro mata M1080.www.pctnew.org.mkv"
results
 ❱ Eye for an Eye (2019)
   skip
   quit
moving to /movies/Quien a hierro mata/~/share/kodi/movies_es/Eye for an Eye (2019).mkv
OK!

1 out of 1 files processed successfully
`

**Comment by jkwill87** [comment]
Should be fixed in the latest version. Run`pip3 install -U mnamer` to update.
