### ISSUE TITLE
very minor issue with uppercase extensions

### ISSUE THREAD

**Issue by fajulleiro** [jkwill87/mnamer#41]
I  found that mnamer doesn't detect media files with uppercase extensions on linux:
`
$ mnamer --id-tmdb=319 movies/True.Romance.1993.Directors.Cut.Bluray.1080p.TrueHD.x264-Grym@BTNET/True.Romance.1993.Directors.Cut.Bluray.1080p.TrueHD.x264-Grym@BTNET.MKV
Starting mnamer
no media files found

$ mnamer --id-tmdb=319 movies/True.Romance.1993.Directors.Cut.Bluray.1080p.TrueHD.x264-Grym@BTNET/true.romance.1993.directors.cut.bluray.1080p.truehd.x264-grym@btnet.mkv
Starting mnamer

Processing Movie "true.romance.1993.directors.cut.bluray.1080p.truehd.x264-grym@btnet.mkv"
results
 ❱ True Romance (1993)
   skip
   quit

`

**Comment by jkwill87** [comment]
This was something I wouldn't even think to check, thanks again 😃

**Comment by jkwill87** [comment]
Should be fixed in the latest version. Run`pip3 install -U mnamer` to update.
