### ISSUE TITLE
Parse Metadata From Directories

### ISSUE THREAD

**Issue by mvrck19** [jkwill87/mnamer#47]
Often media that is downloaded will be in a folder but the folders name might be something like Ford.v.Ferrari.2019.720p.SCREENER.900MB.x264-GalaxyRG[TGx] and renaming it to something like Ford v Ferrari (2019) would be imo better.
I think that it won't be too difficult to pull off and if needed I could help write the code for it

**Comment by jkwill87** [comment]
I felt like this was a thing. If not, you're right, it should be. I'll check it out, thanks!

**Comment by mvrck19** [comment]
I looked up the documentation and what I wanted to do was point mnamer to my folder of movies and rename them
I should have used the -r option instead 
My bad

**Comment by jkwill87** [comment]
Seems like this should be working now :smiley:
