### ISSUE TITLE
ID Field Templating

### ISSUE THREAD

**Issue by travismolick** [jkwill87/mnamer#50]
I was reviewing the options for formatting and wondering if things from themoviedb like "imdb_id" can be added as a option?

example: The Goonies (tt0089218).mp4

**Comment by jkwill87** [comment]
I think that this might already be a thing. If it is I'll document it, if not I'll make sure to add it. Thanks!

**Comment by jkwill87** [comment]
# Update

Should be available in v2.2.0. Please note that ids are only available for the provider currently being used. So to use `imdb_id` for instance you would need to use OMDb.

# Example:

**Command**: `mnamer --movie-api=omdb --movie-format="{name} ({id_imdb}).{extension}" demo/aladdin.2019.avi`
**Result**: `Aladdin (tt6139732).avi`
