### ISSUE TITLE
Add an 'open' command in interactive mode

### ISSUE THREAD

**Issue by Krazybug** [jkwill87/mnamer#53]
When you run the program in interactive mode, you sometimes need to visualize your media before choosing the matching title from a provider.

Could we get an open option to visualize the movie with the default reader ?

**Comment by jkwill87** [comment]
I'm not opposed to this feature but I can't see a good cross-platform way to implement it. I'd rather not add platform-dependent logic to the project as it would introduce branching logic that would be difficult to maintain and near impossible to test. I appreciate the suggestion nonetheless, thank you!

**Comment by Krazybug** [comment]
I'm not sure I was clear. When I meant 'open' I was thinking about the default system player.

os.startfile from the stdlib handles this perfectly, no  ?
