### ISSUE TITLE
[Feature Request] Support for seasons

### ISSUE THREAD

**Issue by TheFrenchGhosty** [jkwill87/mnamer#60]
When importing a season it would be nice to have mnamer recognize it as a whole season without having it recognize every episode one by one.

The solution would be to use the folder name, and the number of video files (so no counting nfo/txt/jpg) in the directory (not the sub-directories).

I personally want to import my content manually (to avoid wrong name) but having to check each episode isn't really convenient.

**Comment by jkwill87** [comment]
I really appreciate the idea, it would be cool, but at this point, I want to avoid trying to make mnamer _too smart_. After thinking it over I don't think that this is something that I'd want to add, at least not now. Here's my rationale:

1. Predictability. As a general design principle, you want your software to be predictable. You expect that each time you run it that it will behave like it did the time before. If a user was tapping away hitting enter one file at a time and then all of a sudden it renames an entire directory that could be a bad experience.

2. Error-prone. My goal for mnamer isn't to always do the right thing but to at least never do the wrong thing. This would have a lot of edge cases and a lot of things that could go wrong.

3. Time. This would be a pretty involved feature to implement and test. At the moment there are a lot of other features on the roadmap to implement that may be more pressing.

In the meantime, users can bulk rename a directory using the `--batch` flag after moving a file or two if they follow a consistent naming pattern.
