### ISSUE TITLE
Remove slashes from title

### ISSUE THREAD

**Issue by paketep** [jkwill87/mnamer#62]
Hi!

Great work, finally something to replace TheRenamer!.

One problem with formats: "{series} {season:02}x{episode:02}{title}{extension}" will produce "The Orville - S01E01 - Old Wounds.mkv" as in your example, but it should produce "The Orville S01E01 Old Wounds.mkv", as there is otherwise no way to remove the slashes. For that file name, the template should have been "{series} - {season:02}x{episode:02} - {title}{extension}" (there is also no spaces between episode and title in the original template).

Also, no paremeter passed should check the current directory.

Thanks!

**Comment by paketep** [comment]
Ok, forget that, it looks like it's an error in the docs and not putting slashes in --episode-format is the solution.

Still, when offering alternatives for the renamed file, it shows the default format and not the one given in the episode-format parameter.

Thanks again!

**Comment by jkwill87** [comment]
> Also, no paremeter passed should check the current directory.

My intention for mnamer is that although it won't always do the right thing, at least it won't do the wrong thing. The reason that this isn't the default behaviour is to prevent users from accidentally processing files, e.g. if they have set batch mode to true in their config file or are a first-time user.

> ... it looks like it's an error in the docs and not putting slashes in --episode-format is the solution

Yep, just a typo on the formatting page. Thanks for pointing that out, I'll go ahead and fix that.
