### ISSUE TITLE
existing files just get overwritten

### ISSUE THREAD

**Issue by n1trux** [jkwill87/mnamer#64]
If you move a file to a directory where a file with the same name already exists with mnamer, the file just gets overwritten without any prompt or notice.

What I'd like to have is a prompt which tells me "The target file already exists, [o]verwrite, [r]ename, [c]ancel?" with a manual input field when choosing to rename.

**Comment by jkwill87** [comment]
> If you move a file to a directory where a file with the same name already exists with mnamer, the file just gets overwritten without any prompt or notice

See the [`no-overwrite` setting](https://github.com/jkwill87/mnamer/wiki/Settings#preferences), this was recently added to prevent this.

> What I'd like to have is a prompt which tells me "The target file already exists, [o]verwrite, [r]ename, [c]ancel?" with a manual input field when choosing to rename.

Yea, I plan on adding a notice if the current file exists. There aren't currently any plans to manually edit files within mnamer, however.
