### ISSUE TITLE
Bug with illegal character

### ISSUE THREAD

**Issue by panosk75** [jkwill87/mnamer#65]
Hi

It looks like illegal characters are not removed before a new folder needs to be created. My series called "Star Trek: Picard" creates this issue. I have the following enabled in the config file, 

 - replace_before = {':': ''}
 - replace_after = {'&': 'and', ':': '', ';': ',', '@': 'at'}

but still issue still there:

Processing Episode "Star Trek Picard - S01E01 - Remembrance.mkv" (2.90GB)?[0m
\\DSL-AC56U\Download2 (at sda)\Complete\Star.Trek.Picard.S01E01.iNTERNAL.REPACK.
1080p.WEB.H264-GHOSTS[rarbg]\Star Trek Picard - S01E01 - Remembrance.mkv
?[33musing tvmaze?[0m

search parameters
 - extension = .mkv
 - group = GHOSTS[RARBG]
 - quality = 1080p web h.264
 - synopsis = None
 - media = episode
 - series = Star Trek Picard
 - season = 1
 - episode = 1
 - date = None
 - title = None
 - id_tvdb = None
 - id_tvmaze = None

results
 ?[35m?[35m??[0m?[0m Star Trek: Picard - 01x01 - Remembrance
   ?[2m?[0m?[4m?[2ms?[0m?[2mkip?[0m
   ?[2m?[0m?[4m?[2mq?[0m?[2muit?[0m
?[A?[A?[A?[?25l?[?12l?[?25h?[B?[B?[B?[32mmoving to \TV\Star Trek: Picard\Season01\Star Trek Picard - Remembrance - S01E01.mkv?[0m

============================== CRASH REPORT BEGIN ==============================

--------------------------------- environment ----------------------------------

 - date = 2020-04-10
 - platform = Windows-7-6.1.7601-SP1
 - arguments = ['--no-guess', '--no-overwrite', '-v', '-r', 'z:\\complete']
 - python version = 3.8.2
 - mnamer version = 2.3.1

--------------------------------- stack trace ----------------------------------

Traceback (most recent call last):
  File "c:\users\panos\appdata\local\programs\python\python38-32\lib\pathlib.py"
, line 1279, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: '\\TV\\Star Trek: Picard\\Season01'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\panos\appdata\local\programs\python\python38-32\lib\pathlib.py"
, line 1279, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: '\\TV\\Star Trek: Picard\\Season01'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\panos\appdata\local\programs\python\python38-32\lib\site-packag
es\mnamer\__main__.py", line 32, in main
    run()
  File "c:\users\panos\appdata\local\programs\python\python38-32\lib\site-packag
es\mnamer\__main__.py", line 157, in run
    target.relocate()
  File "c:\users\panos\appdata\local\programs\python\python38-32\lib\site-packag
es\mnamer\target.py", line 158, in relocate
    self.destination.parent.mkdir(parents=True, exist_ok=True)
  File "c:\users\panos\appdata\local\programs\python\python38-32\lib\pathlib.py"
, line 1283, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "c:\users\panos\appdata\local\programs\python\python38-32\lib\pathlib.py"
, line 1284, in mkdir
    self.mkdir(mode, parents=False, exist_ok=exist_ok)
  File "c:\users\panos\appdata\local\programs\python\python38-32\lib\pathlib.py"
, line 1279, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified:'\\TV\\Star Trek: Picard\\Season01'

=============================== CRASH REPORT END ===============================

Dang, it looks like mnamer crashed! Please consider filling an issue at
https://github.com/jkwill87/mnamer/issues along with this report.

**Comment by jkwill87** [comment]
It seems like this is working for me now in with v2.3.2. Let me know if you're still having problems and I'll check it out.
