### ISSUE TITLE
multiple arguments to --mask

### ISSUE THREAD

**Issue by 2bjc466** [jkwill87/mnamer#66]
help output indicates that --mask should accept a comma-delimited list of strings:

% mnamer -h | grep mask
  --mask=<EXTENSION,...>: only process given file types

they appear to be glued into a single argument:

% mnamer --mask=avi,m4v,mp4,mkv,ts,wmv -v . | grep mask
 - arguments = ['--mask=avi,m4v,mp4,mkv,ts,wmv', '-v', '.']
 - mask = ['.avi,m4v,mp4,mkv,ts,wmv']

this is mnamer 2.3.1 installed on python 3.8.1 via pip.

**Comment by jkwill87** [comment]
The help command formats settings using the standard [POSIX utility conventions](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html). For settings that take multiple arguments, they do not need to be inputted in quotations delimited by commas. If you pass arguments to the mask parameter as positional arguments then this should do what you are looking for.

for example:

```
$ mnamer --mask avi mkv mp4 --verbose
Starting mnamer

system
 - date = 2020-04-14
 - platform = Linux-5.6.2-arch1-2-x86_64-with-glibc2.2.5
 - arguments = ['--mask', 'avi', 'mkv', 'mp4', '--verbose']
 - python version = 3.8.2
 - mnamer version = 2.3.1
 - requests cache = /home/jkwill87/.cache/mnamer-py3.8.sql

settings
 - targets = []
 - batch = False
 - lower = False
 - recurse = False
 - scene = False
 - verbose = True
 - hits = 5
 - ignore = ['.*sample.*', '^RARBG.*']
 - mask = ['.avi', '.mkv', '.mp4']
 - no_cache = False
 - no_guess = False
 - no_overwrite = False
 - no_style = False
 - movie_api = tmdb
 - movie_directory = None
 - movie_format = {name} ({year}){extension}
 - episode_api = tvmaze
 - episode_directory = None
 - episode_format = {series} - S{season:02}E{episode:02} - {title}{extension}
 - version = False
 - config_dump = False
 - config_ignore = False
 - id_imdb = None
 - id_tmdb = None
 - id_tvdb = None
 - id_tvmaze = None
 - media = None
 - test = False
 - api_key_omdb = None
 - api_key_tmdb = None
 - api_key_tvdb = None
 - api_key_tvmaze = None
 - replace_before = {}
 - replace_after = {'&': 'and', '@': 'at', ':': '', ';': ','}

targets
 - None

no media files found
```
