### ISSUE TITLE
SRT files

### ISSUE THREAD

**Issue by SweetthD3ViL** [jkwill87/mnamer#70]
Hi there,

Would it be possible for Mnamer to also rename and move SRT files with the video file?

Also, the wiki explains how to install, what is the best way to keep Mnamer updated? 

Thank you

**Comment by jkwill87** [comment]
> Would it be possible for Mnamer to also rename and move SRT files with the video file?

Proper internationalization support, e.g. subtitles, specifying languages, etc. will probably be the main focus of mnamer v3 but this won't be trivial to implement or be coming anytime in the immediate future.

One possible workaround in the meantime for this was posted for this in #28. If you add the `.srt` extension to `mask` then mnamer will also move subtitle files. This isn't a perfect option given that it will disregard any language information and can overwrite subtitle files if there are multiple ones.

> Also, the wiki explains how to install, what is the best way to keep Mnamer updated?

Probably `pip3 install --user --upgrade mnamer` but it depends on how you installed it. I've updated the wiki with more comprehensive instructions.

**Comment by jkwill87** [comment]
Subtitle support added in [v2.4.1](https://github.com/jkwill87/mnamer/releases/tag/2.4.1) :tada:
