### ISSUE TITLE
Specify Config File

### ISSUE THREAD

**Issue by msw1970** [jkwill87/mnamer#74]
Hi

As per title, is it possible to specify the config file to use on the command line with a preference option?

Thanks

**Comment by jkwill87** [comment]
Sorry no, this is not currently an option.

**[From the wiki](https://github.com/jkwill87/mnamer/wiki/Settings):**
> mnamer attempts to load preferences from a .mnamer-v2.json file in the home directory, the current working directory, and then in each directory up the drive towards the drive root.
