### ISSUE TITLE
episode find at tvdb  doesnt work 

### ISSUE THREAD

**Issue by elschman** [jkwill87/mnamer#75]
It looks like that even with the help of the tvdb id the right episode is not detected. Whats wrong ?

X:\video\serien\MareTv>python -m mnamer --episode-api=tvdb --id-tvdb=190211 --media=episode -v --test Sommer_auf_Neufundland.mp4
Starting mnamer
testing mode

system
 - date = 2020-05-06
 - platform = Windows-10-10.0.18362-SP0
 - arguments = ['--episode-api=tvdb', '--id-tvdb=190211', '--media=episode', '-v', '--test', 'Sommer_auf_Neufundland.mp4']
 - python version = 3.6.8
 - mnamer version = 2.3.4
 - requests cache = C:\xxxxx\AppData\Local\mnamer-py3.6.sql

settings
 - targets = [WindowsPath('Sommer_auf_Neufundland.mp4')]
 - batch = False
 - lower = False
 - recurse = False
 - scene = False
 - verbose = True
 - hits = 5
 - ignore = ['.*sample.*', '^RARBG.*']
 - mask = ['.avi', '.m4v', '.mp4', '.mkv', '.ts', '.wmv']
 - no_cache = False
 - no_guess = False
 - no_overwrite = False
 - no_style = False
 - movie_api = tmdb
 - movie_directory = None
 - movie_format = {name} ({year}){extension}
 - episode_api = tvdb
 - episode_directory = None
 - episode_format = {series} - S{season:02}E{episode:02} - {title}{extension}
 - version = False
 - config_dump = False
 - config_ignore = False
 - id_imdb = None
 - id_tmdb = None
 - id_tvdb = 190211
 - id_tvmaze = None
 - media = episode
 - test = True
 - api_key_omdb = None
 - api_key_tmdb = None
 - api_key_tvdb = None
 - api_key_tvmaze = None
 - replace_before = {}
 - replace_after = {'&': 'and', '@': 'at', ';': ','}

targets
 - xxxxx\MareTv\Sommer_auf_Neufundland.mp4

Processing Episode "Sommer_auf_Neufundland.mp4" (823.82MB)
xxxxx\MareTv\Sommer_auf_Neufundland.mp4
using tvdb

search parameters
 - extension = .mp4
 - group = None
 - quality = None
 - synopsis = None
 - media = episode
 - series = Sommer Auf Neufundland
 - season = None
 - episode = None
 - date = None
 - title = None
 - id_tvdb = 190211
 - id_tvmaze = None

results
 ► 12x02 - Vietnam in the Mekong Delta
   19x13 - 13
   19x14 - 14
   19x15 - 15
   skip
   quit

**Comment by jkwill87** [comment]
`id-tvdb` is used to specify a season id not an episode id
