### ISSUE TITLE
tvdb supports multiple target languages. a parameter should help to request the right language

### ISSUE THREAD

**Issue by elschman** [jkwill87/mnamer#76]
thetvdb.com supports multiple target languages for the tv series. This should be supported by a parameter to be set if en i not the right one.

e.g. --tvdb-lang

**Comment by jkwill87** [comment]
Duplicate of #9. Language and subtitle support will be added in mnamer v3.

**Comment by jkwill87** [comment]
Language support added in [v2.4.1](https://github.com/jkwill87/mnamer/releases/tag/2.4.1) :tada:
