### ISSUE TITLE
Fixed results with differing input

### ISSUE THREAD

**Issue by trapexit** [jkwill87/mnamer#81]
```
$ mnamer --id-tvdb=72514 --media=episode --episode-api=tvdb "Box Car Blues (DVD).mkv"

Processing Episode "Box Car Blues (DVD).mkv" (187.68MB)
results
 ❱ Looney Tunes - 1941x09 - Tortoise Beats Hare
   Looney Tunes - 1941x19 - Hiawatha's Rabbit Hunt
   Looney Tunes - 1941x23 - The Heckling Hare
   Looney Tunes - 1941x30 - All This and Rabbit Stew
   Looney Tunes - 1942x08 - Crazy Cruise
   skip
   quit
```

No matter what the input seems to be it always returns that list. Is mnamer utilizing the name?

**Comment by jkwill87** [comment]
Without parseable series or episode information mnamer is just returning the first results for the season itself. As a workaround if you put these files in a directory named `Looney Toons S1930` you could run something like `mnamer --id-tvdb=72514 'Looney Toons S1930'`. This would give mnamer the series and season which would be enough to work with to match these titles.

IIRC searching by episode title against a given series id is not supported directly by the TVDb or TvMaze APIs. While conceivably this could be accomplished by retrieving metadata for every episode of every season and comparing them against the title within mnamer, I fear that it would likely be untenable in cases such as this as it could potentially require hundreds if not thousands of API calls which would trigger API rate limiting.

Either way, I'll look into this though to see what might be possible. Thanks.

**Comment by trapexit** [comment]
Thanks. I've not looked at the APIs but from what I've seen of other tools there has to be something there. FileBot seems to pull down all the seasons upfront and then do it's own match (though it wasn't always that smart in matching, often missing literal substring matches). These files in particularly are prefixed with numbers for order. I removed it in the example but it was `0005 - Title`.
