### ISSUE TITLE
Language Support

### ISSUE THREAD

**Issue by fajulleiro** [jkwill87/mnamer#9]
I think it would be very nice to add support for other laguages other than english (with fallback to english if the language asked for is not in tvdb for the series). I think that at least tvdb api has some language commands that could be used. 
Many thanks.

**Comment by colemar** [comment]
I would like to always target the original title for any movie, be it english, italian, french, whatever.
I seem to remember that filebot used to have an option for that.

**Comment by jkwill87** [comment]
Language support added in [v2.4.1](https://github.com/jkwill87/mnamer/releases/tag/2.4.1) :tada:
