### ISSUE TITLE
How to pass an API key to Mnamer

### ISSUE THREAD

**Issue by TheFrenchGhosty** [jkwill87/mnamer#91]
The TVDB API seems to require an API key, from what I can see in the code https://github.com/jkwill87/mnamer/blob/master/mnamer/endpoints.py#L251 it looks like mnamer can use a specific API key, the problem is that I can't find any information about how to pass the key to it.

**Comment by jkwill87** [comment]
Thanks for pointing that out, I've updated the wiki [to add that information](https://github.com/jkwill87/mnamer/wiki/Settings#config-only-settings).

**TLDR** you can set `api_key_tvdb` config to use your own key
