### ISSUE TITLE
Edit embedded file metadata

### ISSUE THREAD

**Issue by pike00** [jkwill87/mnamer#94]
This request has nothing to do with the file renaming (which works/no issues), but it would be great if there was also an option to use TVDB/IMDB/etc. to get metadata and set it appropriately. I'm not sure how much use this would be to others (as many people use Plex, Emby, etc. which includes metadata formatted differently), but I think it would be useful to have it wholly contained in the file itself for reproducibility/non-reliance on other services.

**Comment by jkwill87** [comment]
> ability to edit Movie/TV Show metadata simultaneously

> it would be great if there was also an option to use TVDB/IMDB/etc. to get metadata and set it appropriately

> it would be useful to have it wholly contained in the file itself for reproducibility/non-reliance on other services

Its not immediately clear to me how these ideas are related. Would you be able to expand on what you're looking for and how it would work?

Thanks!

**Comment by pike00** [comment]
I'm referring to metadata that is *embedded* in the video file. I'm thinking it would be useful to have these fields show up in Windows Explorer, etc. 

![image](https://user-images.githubusercontent.com/6687499/86818949-05c87d80-c055-11ea-80e1-b225132b5be3.png)

I'm not completely sure how standardized the metadata component of mkv/mp4 containers are, so feel free to say so and I can close the request!

**Comment by jkwill87** [comment]
Oh, okay, got it 👌 

Currently mnamer only edits filenames but not files themselves. Its something that I've thought about writing but to my knowledge there is no straight forward universal method or existing library available to do this. Each file container type, e.g. Matroska, MPEG-4, avi, wmv, etc. each have a different structure and many need to be completely recreated (remuxed) in order to rewrite their metadata. As a result this unfortunately will be unlikely to be implemented in the immediate future.

**Comment by thekiefs** [comment]
I think MKV's metadata can be easily edited with something like mkvpropedit. https://mkvtoolnix.download/doc/mkvpropedit.html

It would be nice to match the rename with the embedded metadata in mnamer so you don't get problems like this: https://apple.stackexchange.com/questions/219699/any-way-to-edit-metadata-of-mkv-files-without-re-encoding

I'm sure it wouldn't be too bad to write in some logic for updating the mkv metadata using dependency MKVToolNix to create something like this:
https://github.com/SLCH/bash-scripts/blob/master/movies/mkvRenameInFolders.sh

However, other containers are probably more complex.

**Comment by jkwill87** [comment]
> It would be nice to match the rename with the embedded metadata in mnamer so you don't get problems like this: https://apple.stackexchange.com/questions/219699/any-way-to-edit-metadata-of-mkv-files-without-re-encoding

Yea, I know, that drives me crazy. I wrote a couple of scripts to strip metadata before calling mnamer to move them.

**strip-mkv.bash**

```bash
#!/bin/bash

while IFS= read -r -d '' file; do
    TITLE=`ffprobe -loglevel 8 -show_entries format_tags=Title -of default=noprint_wrappers=1:nokey=1 "$file"`
    if [ ! -z "$TITLE" ]; then
        echo $TITLE
        mkvpropedit  "$file" -e info -s title=""
    fi
done < <(fd --extension mkv --print0)

```

**strip-mp4.bash**

```bash
#!/bin/bash

while IFS= read -r -d '' file; do
    TITLE=`ffprobe -loglevel 8 -show_entries format_tags=Title -of default=noprint_wrappers=1:nokey=1 "$file"`
    if [ ! -z "$TITLE" ]; then
        echo "$TITLE"
        rm -f /tmp/tmp.mp4
        ffmpeg -nostdin -loglevel panic -i "$file" -c copy -metadata title="" /tmp/tmp.mp4
        mv /tmp/tmp.mp4 "$file"
    fi
done < <(fd --extension mp4 --print0)
```

> I think MKV's metadata can be easily edited with something like mkvpropedit. https://mkvtoolnix.download/doc/mkvpropedit.html

So yea, I use mkvpropedit and ffmpeg myself to edit embedded metadata myself. It works great for me but won't for Windows users, those who use other container types, or have not installed these dependencies. The goal here is to be able to run `pip install mnamer; mnamer .` and it just work so long as your system has Python.
