### ISSUE TITLE
Movie Split into 2 parts

### ISSUE THREAD

**Issue by weekender23** [jkwill87/mnamer#97]
hi

is there anyway to rename and move a movie file when the movie is split into two parts?

For example a movie is named like this:
filename-cd1.avi 
filename-cd2.avi

i want the movie files to be named like this or something similar to this:
filename-year-1.avi
filename-year-2.avi

thanks.

**Comment by jkwill87** [comment]
Sorry, that is not a current or planned feature for mnamer at this time.
